import type { MediaItem, WallManifest } from "./types";

/**
 * Stand-in for `GET /walls/:id/manifest` (see docs/ARCHITECTURE.md §4/§6).
 * Files here are generated by `scripts/generate-mock-assets.mjs` — keep the
 * two in sync if you add/rename items.
 *
 * `focalPoint` is normalized 0..1 and anchors the Ken-Burns pan/zoom and the
 * CSS `object-position` crop, mirroring the real pipeline's saliency-based
 * focal point (docs/ARCHITECTURE.md §4).
 *
 * `frameSize` is the creator's chosen display ratio (`frameSizes.ts`) —
 * mixed deliberately across 9:16/3:4/1:1/4:3/16:9 here to demonstrate the
 * feature, skewing toward 9:16 for the "home movie" video clips the way a
 * real family's phone-shot footage would skew today.
 *
 * Captions are deliberately a little poetic rather than literal photo
 * titles — every frame style now displays them (see frames.css), so
 * they're worth making worth reading.
 */

const media = (partial: Omit<MediaItem, "thumbnailUrl" | "displayUrl"> & { file: string; dir: "photos" | "videos" }): MediaItem => ({
  ...partial,
  thumbnailUrl: `media/${partial.dir}/${partial.file}`,
  displayUrl: `media/${partial.dir}/${partial.file}`,
});

const PHOTOS: MediaItem[] = [
  media({ id: "photo-01", file: "photo-01.svg", dir: "photos", kind: "photo", aspectRatio: 4 / 3, frameSize: "4:3", focalPoint: { x: 0.4, y: 0.4 }, dominantColor: "#c65b2e", label: "Where the lake kissed the sky" }),
  media({ id: "photo-02", file: "photo-02.svg", dir: "photos", kind: "photo", aspectRatio: 3 / 4, frameSize: "3:4", focalPoint: { x: 0.5, y: 0.35 }, dominantColor: "#3c6b93", label: "Backpack bigger than the kid inside it" }),
  media({ id: "photo-03", file: "photo-03.svg", dir: "photos", kind: "photo", aspectRatio: 1, frameSize: "1:1", focalPoint: { x: 0.45, y: 0.4 }, dominantColor: "#4f7a3d", label: "Grandma's hands, forever green" }),
  media({ id: "photo-04", file: "photo-04.svg", dir: "photos", kind: "photo", aspectRatio: 3 / 4, frameSize: "3:4", focalPoint: { x: 0.5, y: 0.4 }, dominantColor: "#a85c43", label: "Seconds before the food fight" }),
  media({ id: "photo-05", file: "photo-05.svg", dir: "photos", kind: "photo", aspectRatio: 16 / 9, frameSize: "16:9", focalPoint: { x: 0.4, y: 0.4 }, dominantColor: "#b5762f", label: "Windows down, nowhere to be" }),
  media({ id: "photo-06", file: "photo-06.svg", dir: "photos", kind: "photo", aspectRatio: 9 / 16, frameSize: "9:16", focalPoint: { x: 0.5, y: 0.3 }, dominantColor: "#3f2f6e", label: "Countdown to forever" }),
  media({ id: "photo-07", file: "photo-07.svg", dir: "photos", kind: "photo", aspectRatio: 4 / 3, frameSize: "4:3", focalPoint: { x: 0.45, y: 0.42 }, dominantColor: "#8f3e21", label: "Smoke, laughter, one burnt burger" }),
  media({ id: "photo-08", file: "photo-08.svg", dir: "photos", kind: "photo", aspectRatio: 1, frameSize: "1:1", focalPoint: { x: 0.5, y: 0.4 }, dominantColor: "#276b74", label: "Salt in our hair, sun on our skin" }),
  media({ id: "photo-09", file: "photo-09.svg", dir: "photos", kind: "photo", aspectRatio: 9 / 16, frameSize: "9:16", focalPoint: { x: 0.5, y: 0.3 }, dominantColor: "#7a2f45", label: "Still in pajamas, already celebrating" }),
  media({ id: "photo-10", file: "photo-10.svg", dir: "photos", kind: "photo", aspectRatio: 1, frameSize: "1:1", focalPoint: { x: 0.5, y: 0.4 }, dominantColor: "#a3651c", label: "Make a wish" }),
  media({ id: "photo-11", file: "photo-11.svg", dir: "photos", kind: "photo", aspectRatio: 4 / 3, frameSize: "4:3", focalPoint: { x: 0.42, y: 0.4 }, dominantColor: "#6e3a1d", label: "Crunching through golden afternoons" }),
  media({ id: "photo-12", file: "photo-12.svg", dir: "photos", kind: "photo", aspectRatio: 16 / 9, frameSize: "16:9", focalPoint: { x: 0.5, y: 0.4 }, dominantColor: "#5b7f92", label: "The world went quiet and white" }),
];

const VIDEOS: MediaItem[] = [
  media({ id: "video-01", file: "video-01.mp4", dir: "videos", kind: "video", aspectRatio: 9 / 16, frameSize: "9:16", focalPoint: { x: 0.5, y: 0.5 }, dominantColor: "#b5451f", label: "Confetti, thrown too early" }),
  media({ id: "video-02", file: "video-02.mp4", dir: "videos", kind: "video", aspectRatio: 9 / 16, frameSize: "9:16", focalPoint: { x: 0.5, y: 0.5 }, dominantColor: "#2c5f7c", label: "The sun said goodnight first" }),
  media({ id: "video-03", file: "video-03.mp4", dir: "videos", kind: "video", aspectRatio: 9 / 16, frameSize: "9:16", focalPoint: { x: 0.5, y: 0.5 }, dominantColor: "#2a1f4d", label: "Sky full of tiny suns" }),
  media({ id: "video-04", file: "video-04.mp4", dir: "videos", kind: "video", aspectRatio: 16 / 9, frameSize: "16:9", focalPoint: { x: 0.5, y: 0.5 }, dominantColor: "#3c5a2c", label: "Where the tomatoes grew wild" }),
];

export function loadMockManifest(): WallManifest {
  return {
    wallId: "demo-wall",
    frameStyleKit: "heirloom",
    layoutSeed: 20240601,
    media: [...PHOTOS, ...VIDEOS],
  };
}
